#!/usr/bin/env python3
"""
Search RCSB PDB for (target protein) AND (nanobody/VHH terms) for a list of proteins in an Excel file.

Input:  an Excel file with a column containing gene/protein names (default: Human_Symbol)
Output: two files:
  1) summary CSV: one row per target with hit counts and first N PDB IDs
  2) long CSV:    one row per (target, PDB ID) hit

This uses the RCSB Search API v2 endpoint:
  https://search.rcsb.org/rcsbsearch/v2/query

Docs:
  - Search API overview: https://search.rcsb.org/
  - Basic/full-text query grammar: https://www.rcsb.org/docs/search-and-browse/basic-search

Author: (generated by ChatGPT)
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from typing import Any, Dict, List, Tuple

import pandas as pd
import requests


SEARCH_URL = "https://search.rcsb.org/rcsbsearch/v2/query"

# Your requested nanobody terms. You can extend this (e.g., "camelid", "VHH domain", "nanobody®", etc.)
NANOBODY_QUERY = 'nanobody | VHH | "single-domain antibody"'


def build_query(target: str, mode: str) -> Dict[str, Any]:
    """
    Build an RCSB Search API query.

    mode:
      - "gene_attr": attribute search on rcsb_entity_source_organism.rcsb_gene_name.value (case-sensitive)
      - "basic":     unstructured full_text basic search: target + (nanobody terms)
    """
    if mode == "gene_attr":
        target_node = {
            "type": "terminal",
            "service": "text",
            "parameters": {
                "attribute": "rcsb_entity_source_organism.rcsb_gene_name.value",
                "operator": "exact_match",
                "value": target,
                "case_sensitive": True,
            },
        }
        nanobody_node = {
            "type": "terminal",
            "service": "full_text",
            "parameters": {"value": NANOBODY_QUERY},
        }
        query = {
            "query": {
                "type": "group",
                "logical_operator": "and",
                "nodes": [target_node, nanobody_node],
            },
            "return_type": "entry",
            "request_options": {
                "paginate": {"start": 0, "rows": 10000},
                "results_verbosity": "compact",
            },
        }
        return query

    if mode == "basic":
        # Basic-search grammar supports '+' for AND and '|' for OR, plus parentheses.
        # Example: ABL1 + (nanobody | VHH | "single-domain antibody")
        basic_value = f'{target} + ( {NANOBODY_QUERY} )'
        return {
            "query": {"type": "terminal", "service": "full_text", "parameters": {"value": basic_value}},
            "return_type": "entry",
            "request_options": {
                "paginate": {"start": 0, "rows": 10000},
                "results_verbosity": "compact",
            },
        }

    raise ValueError(f"Unknown mode: {mode}")


def post_json_with_retries(session: requests.Session, url: str, payload: Dict[str, Any],
                           max_retries: int = 6, backoff: float = 1.5) -> requests.Response:
    """
    Robust POST with exponential backoff for transient failures (429/5xx).
    """
    data = json.dumps(payload)
    headers = {"Content-Type": "application/json"}

    for attempt in range(max_retries):
        resp = session.post(url, data=data, headers=headers, timeout=60)
        if resp.status_code in (200, 204):
            return resp
        if resp.status_code in (429, 500, 502, 503, 504):
            sleep_s = backoff ** attempt
            time.sleep(sleep_s)
            continue
        # Hard failure
        resp.raise_for_status()

    # If we exhausted retries, raise the last status
    resp.raise_for_status()
    return resp  # unreachable


def run_one_target(session: requests.Session, target: str, delay_s: float = 0.05) -> Tuple[str, List[str], str]:
    """
    Try gene-attribute mode first, then fall back to basic full-text if no hits.
    Returns (target, pdb_ids, used_mode).
    """
    for mode in ("gene_attr", "basic"):
        q = build_query(target, mode)
        resp = post_json_with_retries(session, SEARCH_URL, q)

        if resp.status_code == 204:
            pdb_ids: List[str] = []
        else:
            j = resp.json()
            result_set = j.get("result_set", [])
            # Depending on results_verbosity/API behavior, each entry may be either
            # a dict with an "identifier" key or a bare identifier string.
            pdb_ids = [r["identifier"] if isinstance(r, dict) else r for r in result_set]

        if pdb_ids:
            time.sleep(delay_s)
            return target, pdb_ids, mode

    time.sleep(delay_s)
    return target, [], "none"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("excel", help="Input Excel file (e.g., your_list.xlsx)")
    ap.add_argument("--column", default="Human_Symbol",
                    help="Column containing target names (default: Human_Symbol)")
    ap.add_argument("--max_ids_per_target", type=int, default=200,
                    help="Store up to this many PDB IDs per target in long output (default: 200)")
    ap.add_argument("--out_prefix", default="rcsb_nanobody_hits",
                    help="Output prefix for CSVs (default: rcsb_nanobody_hits)")
    args = ap.parse_args()

    df = pd.read_excel(args.excel)
    if args.column not in df.columns:
        raise SystemExit(f"Column '{args.column}' not found. Available: {list(df.columns)}")

    targets = (
        df[args.column]
        .dropna()
        .astype(str)
        .str.strip()
        .replace("", pd.NA)
        .dropna()
        .unique()
        .tolist()
    )

    summary_rows = []
    long_rows = []

    with requests.Session() as session:
        for t in targets:
            target, pdb_ids, mode = run_one_target(session, t)
            # summarize
            summary_rows.append({
                "target": target,
                "used_mode": mode,
                "n_hits": len(pdb_ids),
                "pdb_ids_first_50": ",".join(pdb_ids[:50]),
            })

            # long format (cap per target)
            for pid in pdb_ids[: args.max_ids_per_target]:
                long_rows.append({"target": target, "pdb_id": pid, "used_mode": mode})

    summary = pd.DataFrame(summary_rows).sort_values(["n_hits", "target"], ascending=[False, True])
    long_df = pd.DataFrame(long_rows)

    summary_path = f"{args.out_prefix}_summary.csv"
    long_path = f"{args.out_prefix}_long.csv"
    summary.to_csv(summary_path, index=False)
    long_df.to_csv(long_path, index=False)

    print(f"Wrote: {summary_path}")
    print(f"Wrote: {long_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
